# Generated by Django 5.2.1 on 2025-06-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbdmsapp', '0007_donorreg_status_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'requester'), (2, 'donor'), (1, 'admin')], default=1, max_length=50),
        ),
    ]
