# Generated by Django 5.2.1 on 2025-06-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbdmsapp', '0008_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'donor'), (3, 'requester'), (1, 'admin')], default=1, max_length=50),
        ),
        migrations.AlterModelTable(
            name='bloodgroup',
            table='bloodgroup',
        ),
    ]
