# Generated by Django 5.2.1 on 2025-06-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbdmsapp', '0009_alter_customuser_user_type_alter_bloodgroup_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorreg',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='donorreg',
            name='status',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterModelTable(
            name='bloodgroup',
            table=None,
        ),
    ]
