# Generated by Django 5.2.1 on 2025-06-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbdmsapp', '0011_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'donor'), (3, 'requester'), (1, 'admin')], default=1, max_length=50),
        ),
    ]
